# Generated by Django 5.0 on 2023-12-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cron_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "Врач", "verbose_name_plural": "Врачи"},
        ),
        migrations.AddField(
            model_name="doctor",
            name="clinic",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cron_backend.service"
            ),
        ),
    ]
