# Generated by Django 4.2.7 on 2023-12-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cron_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='title',
        ),
    ]
