# Generated by Django 5.0 on 2023-12-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cron_backend", "0002_service_alter_doctor_options_doctor_clinic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("location", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Клиника",
                "verbose_name_plural": "Клиники",
            },
        ),
        migrations.RenameModel(
            old_name="Service",
            new_name="Specialist",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="specialization",
            new_name="speciality",
        ),
        migrations.RenameField(
            model_name="specialist",
            old_name="name",
            new_name="type",
        ),
    ]
