# Generated by Django 5.0 on 2023-12-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cron_backend", "0003_clinic_rename_service_specialist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cron_backend.clinic"
            ),
        ),
    ]
